# Generated by Django 3.0.3 on 2020-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countarray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField(blank=True, null=True)),
                ('countarray', models.TextField(blank=True, db_column='countArray', null=True)),
            ],
            options={
                'db_table': 'countArray',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, db_column='DESC', null=True)),
            ],
            options={
                'db_table': 'DESC',
                'managed': False,
            },
        ),
    ]
